### ISSUE TITLE
[URGENT] BLANK PAYMENT PAGE ON PRESTASHOP

### ISSUE THREAD

**Issue by iloukou** [DPO-Group/DPO_PrestaShop#3]
Hi i have an blank page on the payment page of the prestashop intégration. I run prestashop 1.7.8 and i notice that your plugin is for prestashop 1.7.7 .
Thank you to give rapidly. I need to get in production as soon as possible. 

My Shop is easydietci.com

**Comment by bruce-atkinson** [comment]
Hi @iloukou 

Please contact the [DPO Group support team](https://dpogroup.com/contact-us/) should you require any assistance.
